/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.io.File;
import java.io.FileInputStream;
//import java.io.FileOutputStream;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author victorhuertas
 */
public class frmRegistroSecuenciaFasta extends javax.swing.JInternalFrame {

    private String PrimerFasta="x", SegundoFasta="x";
    private JFileChooser seleccionar = new JFileChooser();
    private File archivo;
    private FileInputStream entrada;
    //private FileOutputStream salida;

    /**
     * Creates new form DigitalizacionSecuencia
     */
    public frmRegistroSecuenciaFasta() {
        initComponents();
        getLblPrimerGuardado().setVisible(false);
        getLblSegundoGuardado().setVisible(false);
    }

    public String AbrirArchivo(File archivo) {
        String fasta = "";
        try {
            entrada = new FileInputStream(archivo);
            int ascci;
            while ((ascci = entrada.read()) != -1) {
                char caracter = (char) ascci;
                fasta += caracter;
            }
        } catch (Exception e) {
        }
        return fasta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPrimerFasta = new javax.swing.JButton();
        btnSegundoFasta = new javax.swing.JButton();
        lblPrimerGuardado = new javax.swing.JLabel();
        lblSegundoGuardado = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();

        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(0, 123, 82));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Secuenciación FASTA");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(100, 110, 219));
        jPanel2.setToolTipText("");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Suba aquí el primer archivo Fasta:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Suba aquí el segundo archivo Fasta: ");

        btnPrimerFasta.setBackground(new java.awt.Color(102, 102, 102));
        btnPrimerFasta.setForeground(new java.awt.Color(255, 255, 255));
        btnPrimerFasta.setText("Abrir Primer Fasta");
        btnPrimerFasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimerFastaActionPerformed(evt);
            }
        });

        btnSegundoFasta.setBackground(new java.awt.Color(102, 102, 102));
        btnSegundoFasta.setForeground(new java.awt.Color(255, 255, 255));
        btnSegundoFasta.setText("Abrir Segundo Fasta");
        btnSegundoFasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSegundoFastaActionPerformed(evt);
            }
        });

        lblPrimerGuardado.setForeground(new java.awt.Color(150, 150, 150));
        lblPrimerGuardado.setText("*Seleccionado");

        lblSegundoGuardado.setForeground(new java.awt.Color(150, 150, 150));
        lblSegundoGuardado.setText("*Seleccionado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPrimerFasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSegundoFasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSegundoGuardado)
                    .addComponent(lblPrimerGuardado))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnPrimerFasta)
                    .addComponent(lblPrimerGuardado))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnSegundoFasta)
                    .addComponent(lblSegundoGuardado))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnEnviar.setBackground(new java.awt.Color(102, 102, 102));
        btnEnviar.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(btnEnviar)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviar)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimerFastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimerFastaActionPerformed
        // TODO add your handling code here:
        if (seleccionar.showDialog(null, "Abrir") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionar.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("fasta")) {
                    PrimerFasta = AbrirArchivo(archivo);
                    //txtarea.SetText(documento);
                    getLblPrimerGuardado().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Archivo no compatible, recuerde que debe ser archivo FASTA");
                }
            }
        }
    }//GEN-LAST:event_btnPrimerFastaActionPerformed

    private void btnSegundoFastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegundoFastaActionPerformed
        // TODO add your handling code here:
        if (seleccionar.showDialog(null, "Abrir") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionar.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("fasta")) {
                    SegundoFasta = AbrirArchivo(archivo);
                    //txtarea.SetText(documento);
                    getLblSegundoGuardado().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Archivo no compatible, recuerde que debe ser archivo FASTA");
                }
            }
        }
    }//GEN-LAST:event_btnSegundoFastaActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnPrimerFasta;
    private javax.swing.JButton btnSegundoFasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPrimerGuardado;
    private javax.swing.JLabel lblSegundoGuardado;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnPrimerFasta() {
        return btnPrimerFasta;
    }

    public void setBtnPrimerFasta(JButton btnPrimerFasta) {
        this.btnPrimerFasta = btnPrimerFasta;
    }

    public JButton getBtnSegundoFasta() {
        return btnSegundoFasta;
    }

    public void setBtnSegundoFasta(JButton btnSegundoFasta) {
        this.btnSegundoFasta = btnSegundoFasta;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public String getPrimerFasta() {
        return PrimerFasta;
    }

    public void setPrimerFasta(String PrimerFasta) {
        this.PrimerFasta = PrimerFasta;
    }

    public String getSegundoFasta() {
        return SegundoFasta;
    }

    public void setSegundoFasta(String SegundoFasta) {
        this.SegundoFasta = SegundoFasta;
    }

    public JLabel getLblPrimerGuardado() {
        return lblPrimerGuardado;
    }

    public void setLblPrimerGuardado(JLabel lblPrimerGuardado) {
        this.lblPrimerGuardado = lblPrimerGuardado;
    }

    public JLabel getLblSegundoGuardado() {
        return lblSegundoGuardado;
    }

    public void setLblSegundoGuardado(JLabel lblSegundoGuardado) {
        this.lblSegundoGuardado = lblSegundoGuardado;
    }

    public JButton getBtnEnviar() {
        return btnEnviar;
    }

    public void setBtnEnviar(JButton btnEnviar) {
        this.btnEnviar = btnEnviar;
    }
    
    

}
